// Code generated by Kitex v0.8.0. DO NOT EDIT.
package test

import (
	server "github.com/cloudwego/kitex/server"
	test "rpc/kitex_gen/test"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler test.Test, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
